### ISSUE TITLE
Width not consistent throughout BS.

### ISSUE THREAD

**Issue by N6REJ** [N6REJ/ae-template#33]
If there is a container under a container then due to BS's inclusion of 
```css
.container{
padding-left: 15px;
padding-right: 15px;
}
```
the containers will indent throwing the overall look off.  By adding a control we are able to fixate the width better.  Doing so separately prevents internal content areas ( like content-area .container ) to lose their edge padding.  Yet still allows the external padding to be controlled.
It might be more viable to limit the header itself.. this should be investigated as well.

**Comment by N6REJ** [comment]
removing #header .container from 
```css
header#header.container, .breadcrumb, #content-area, .navbar-collapse {
background: #222;
border: 0px;
border-radius: 8px;
-webkit-box-shadow: inset 0px 0px 8px 1px #000000;
-moz-box-shadow: inset 0px 0px 8px 1px #000000;
box-shadow: inset 0px 0px 8px 1px #000000;
}
```
resolves the issue but of course removes the styling.
