### ISSUE TITLE
strange menu item border styling

### ISSUE THREAD

**Issue by N6REJ** [N6REJ/ae-template#42]
is this right?
````css
 .nav>li>span.nav-header{
	border-right:1px solid rgba(0,0,0,0.2);
	border-left:1px solid rgba(255,255,255,0.1);
} 
```` 
 looks strange.  why 2 separate colors?
