### ISSUE TITLE
remove coloring for menu's to styles

### ISSUE THREAD

**Issue by N6REJ** [N6REJ/ae-template#45]
in Alterego we have some menu coloring in alterego.css, this can't be there as it overrides what the style is doing.  Remove it and if necessary add it to the style.
```css
/* match span and header to a on focus *//*
.nav>li>span.nav-header:hover, .nav>li>span.header:focus,.nav>li>span.separator:hover, .nav>li>span.separator:focus{
	background-color: #303030;
	color: #0ce3ac;	
}*/

#menu .nav.menu.navbar-nav > li > span.nav-header:hover,
#menu .nav.menu.navbar-nav > li.parent:hover > span.nav-header,
#menu .nav.menu.navbar-nav > li.active.parent > span.nav-header{
	background: #3a8f02;
	color:#fff;
}
```
