### ISSUE TITLE
Remove coloring for go-to-top in jbackbone.css

### ISSUE THREAD

**Issue by N6REJ** [N6REJ/ae-template#58]
jbackbone.css has styling for go-to-top, best to remove it so it follows swatches behavior
```css
/* start back to top */
a.go-top {
	color:#FFF;
}

.go-top {
	position:fixed;
	bottom:2em;
	right:2em;
	text-decoration:none;
	color:#FFF;
	background-color:rgba(0,0,0,0.3);
	font-size:12px;
	padding:1em;
	display:none;
	z-index:9999;
}

/* end back to top */
```
