### ISSUE TITLE
Remove coloring for strange buttons in jbackbone.css

### ISSUE THREAD

**Issue by N6REJ** [N6REJ/ae-template#59]
Not sure exactly what this code does, but we need to remove the color styling...
```css
.portfolio-nav .joostrap.btn-group a.btn {
	border:1px solid #eaeaea;
	border-bottom:1px solid #d8d8d8;
	padding:8px 15px;
	text-align:left;
	min-width:150px;
	background:#f5f5f5;
	background:-moz-linear-gradient(top,#fff 0%,#f7f7f7 100%);
	background:-webkit-gradient(linear,left top,left bottom,color-stop(0%,#fff),color-stop(100%,#f7f7f7));
	background:-webkit-linear-gradient(top,#fff 0%,#f7f7f7 100%);
	background:-o-linear-gradient(top,#fff 0%,#f7f7f7 100%);
	background:-ms-linear-gradient(top,#fff 0%,#f7f7f7 100%);
	background:linear-gradient(to bottom,#fff 0%,#f7f7f7 100%);
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffffff',endColorstr='#f7f7f7',GradientType=0);
}
```
