### ISSUE TITLE
remove coloring for navbar from jbackbone.css

### ISSUE THREAD

**Issue by N6REJ** [N6REJ/ae-template#61]
several lines of color styling in jbackbone.css related to color styling.
```css

.navbar .sub-menu:before {
	border-bottom:7px solid transparent;
	border-left:none;
	border-right:7px solid rgba(0,0,0,0.2);
	border-top:7px solid transparent;
	left:-7px;
	top:10px;
}

.navbar .sub-menu:after {
	border-top:6px solid transparent;
	border-left:none;
	border-right:6px solid #fff;
	border-bottom:6px solid transparent;
	left:10px;
	top:11px;
	left:-6px;
}

.dropdown-submenu {
	position:relative;
}

.nav-justified>.dropdown>ul.nav-child.dropdown-menu {
	margin-top:0;
	margin-left:0;
	top:auto;
	left:0;
	width:100%;
}

.nav-justified>.dropdown .dropdown-menu {
	top:0;
	left:100%;
	margin-top:-6px;
	margin-left:-1px;
}

.dropdown-submenu>.dropdown-menu {
	top:0;
	left:100%;
	margin-top:-6px;
	margin-left:-1px;
	-webkit-border-radius:0 6px 6px;
	-moz-border-radius:0 6px 6px;
	border-radius:0 6px 6px;
}

.dropdown-submenu>a:after {
	display:block;
	content:" ";
	float:right;
	width:0;
	height:0;
	border-color:transparent;
	border-style:solid;
	border-width:5px 0 5px 5px;
/* border-left-color:#ccc; */
	margin-top:5px;
	margin-right:-10px;
}
```
